### ISSUE TITLE
Use Structured Data for FAQ for SEO

### ISSUE THREAD

**Issue by aaronmgdr** [AlexBHarley/celofaq#1]
Structured data will help people find the answers to their questions when searching via a search engine.

https://developers.google.com/search/docs/data-types/faqpage

Hard part is that right now the content is mixed with the html/components. possible solution is plain text in json with `{title, body}` but that would have us lose linking and formating of body. Maybe an array of json with body field as markdown would work?

**Comment by AlexBHarley** [comment]
Oh cool! Didn't know about that. 

I see the easiest way to work with existing code is just passing the additional props (e.g. `itemprop="mainEntity" itemtype="https://schema.org/Question"`) but maybe makes sense to have an array shared between the `<head />` and main content. That would still allow formatting with HTML.
